# Generated by release script
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvkeystoregen
LOCAL_SRC_FILES := host/linux-x86/bin/nvkeystoregen
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvtegrasign
LOCAL_SRC_FILES := host/linux-x86/bin/nvtegrasign
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvtegrasecuretool
LOCAL_SRC_FILES := host/linux-x86/bin/nvtegrasecuretool
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := python
LOCAL_SRC_FILES := target/product/shieldtablet/bin/python
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bootloader
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/bootloader.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tlk_daemon
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/tlk_daemon
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ussrd
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/ussrd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libgov_graphics libgov_combinator libgov_camera libgov_spincircle libc libgov_boot libphs libm libgov_force libstdc++ liblog libgov_il libgov_ui libussrd libgov_generic libgov_tbc libgov_gpucompute libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := pbc
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/pbc
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libutils libm libc libstdc++ libcutils libnativehelper libc libcutils libm libnativehelper libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nv_hciattach
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/nv_hciattach
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := downloader
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/downloader
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libm libc libstdc++ libdl libcutils libstlport libc libcutils libdl libm libstdc++ libstlport
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-feedback
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-feedback
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-loader
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-loader
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera_log_serial_arm
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera_log_serial_arm
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-switcherd
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-switcherd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libcutils libm libusbhost libc libcutils libm libstdc++ libusbhost
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegrastats
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/tegrastats
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libutils libm libc libnvrm_graphics libstdc++ libcutils liblog libc libcutils liblog libm libnvrm_graphics libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := raydium_selftest
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/raydium_selftest
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp_test
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/hdcp_test
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-crashlogs
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-crashlogs
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libcutils libm libc libcutils libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rm_test
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/rm_test
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := btmacwriter
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/btmacwriter
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libstdc++ libcutils libm libc libcutils libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := crash-check-arm
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/crash-check-arm
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rm_ts_server
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/rm_ts_server
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-config
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/icera-config/icera-config.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/icera-config
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NvCPLUpdater
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/NvCPLUpdater/NvCPLUpdater.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/NvCPLUpdater
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NvBenchmarkBlocker
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/NvBenchmarkBlocker/NvBenchmarkBlocker.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/NvBenchmarkBlocker
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NvCPLSvc
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/NvCPLSvc/NvCPLSvc.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/NvCPLSvc
LOCAL_REQUIRED_MODULES := libnvcontrol_jni com.nvidia.NvCPLSvc.api
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/app/NvCPLSvc/NvCPLSvc.apk_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := IceraDebugAgent
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/IceraDebugAgent/IceraDebugAgent.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/IceraDebugAgent
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := QuadDSecurityService
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/QuadDSecurityService/QuadDSecurityService.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app/QuadDSecurityService
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvoice
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvoice.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libaudioutils libm libc libstdc++ libcutils libutils libicuuc libaudioutils libc libcutils libicuuc libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvwsi
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvwsi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics liblog libnvgr libhardware libsync libc libhardware liblog libm libnvgr libnvos libnvrm libnvrm_graphics libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdrmdecrypt
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libdrmdecrypt.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstagefright_foundation libstdc++ liblog libnvavp libc liblog libm libnvavp libnvos libnvrm libstagefright_foundation libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameratools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcameratools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libscf libm libc libnvrm libnvmm_utils libcutils libhardware libutils libnvrm_graphics libnvcam_imageencoder libnvddk_2d_v2 libstlport libc libcutils libhardware libm libnvcam_imageencoder libnvddk_2d_v2 libnvmm_utils libnvos libnvrm libnvrm_graphics libscf libstdc++ libstlport libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvglsi
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvglsi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvwsi libm libz libc libstdc++ libdl libc libdl libm libnvwsi libstdc++ libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcpl
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcpl.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libbinder libstdc++ libcutils libbinder libc libcutils libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvhwc_service
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhwc_service.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libbinder libstdc++ libcutils libbinder libc libcutils libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomxadaptor
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomxadaptor.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libui libmedia libm libc libbinder libstdc++ libcutils libhardware libstagefright libbinder libc libcutils libhardware libm libmedia libstagefright libstdc++ libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvme_msenc
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvme_msenc.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvrm_graphics libnvddk_2d_v2 libc libm libnvddk_2d_v2 libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtsec_wrapper
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtsec_wrapper.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics liblog libc liblog libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvapputil
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvapputil.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvos libm libc libm libnvos libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtestresults
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtestresults.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvtestio libnvos libm libc libm libnvos libnvtestio libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvsm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvsm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_04_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_04_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvvicsi_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvvicsi_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liboemcrypto
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/liboemcrypto.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ liblog libnvavp libstlport
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_video
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_video.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmmlite_utils libstdc++ libcuda libnvmmlite libm libc libnvrm libnvmm_utils libnvrm_graphics libnvtvmr libnvtnr libnvos libnvparser libnvavp libnvfusebypass libnvddk_2d_v2 libc libcuda libm libnvavp libnvddk_2d_v2 libnvfusebypass libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvparser libnvrm libnvrm_graphics libnvtnr libnvtvmr libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvaudiofx
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvaudiofx.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libstdc++ libcutils libicuuc libc libcutils libicuuc libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudiopolicymanager
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libaudiopolicymanager.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libaudiopolicymanagerdefault libstdc++ libcutils liblog libsoundtrigger libaudiopolicymanagerdefault libc libcutils liblog libm libsoundtrigger libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librm_ts_service
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/librm_ts_service.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudioavp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libaudioavp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libmedia libnvos libm libhardware_legacy libc libbinder libnvrm libstdc++ libcutils libnvrm_graphics libnvavp libbinder libc libcutils libhardware_legacy libm libmedia libnvavp libnvos libnvrm libnvrm_graphics libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_writer
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_writer.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvmm_contentpipe libc libm libnvmm_contentpipe libnvmm_utils libnvos libnvrm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libnvos libm libc libstdc++ libcutils libc libcutils libm libnvos libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_image
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_image.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmmlite_utils libstdc++ libnvtvmr libnvmmlite libm libc libnvrm libnvmm_utils libnvrm_graphics libnvos libnvparser libnvddk_2d_v2 libc libm libnvddk_2d_v2 libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvparser libnvrm libnvrm_graphics libnvtvmr libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomxilclient
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomxilclient.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvos libm libc libm libnvos libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libfcamdng
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libfcamdng.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libcutils liblog libcutils liblog
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvaudioservice
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvaudioservice.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libbinder libstdc++ libcutils libbinder libc libcutils libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libglcore
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libglcore.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libz libnvrmapi_tegra libc libstdc++ libnvcpl libcutils libdl libnvglsi libc libcutils libdl libm libstdc++ libutils libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcamerahdr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmm_utils libcutils libopencv24_tegra libnvos libnvrm libcutils libnvmm_utils libnvos libnvrm libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvcamerahdr.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_camera
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_camera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libEGL libnvtvmr libnvos libGLESv2 libjpeg libnvodm_imager libnvisp libnvvicsi libnvrm libnvsm libnvmm_utils libcutils libopencv24_tegra libnvrm_graphics libnvmm libnvddk_2d_v2 libEGL libGLESv2 libcutils libjpeg libnvddk_2d_v2 libnvisp libnvmm libnvmm_utils libnvodm_imager libnvos libnvrm libnvrm_graphics libnvsm libnvtvmr libnvvicsi libopencv24_tegra
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_force
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_force.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvstitching
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvstitching.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := liblog libopencv24_tegra liblog libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvstitching.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_camera_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_camera_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libEGL libcuda libnvisp_v3 libGLESv2 libdl libjpeg libnvrm libnvsm libnvvicsi_v3 libnvmm_utils libgui libcutils libnvtvmr libutils libnvodm_imager libopencv24_tegra libnvos libnvrm_graphics libnvmm libnvddk_2d_v2 libEGL libGLESv2 libcuda libcutils libdl libgui libjpeg libnvddk_2d_v2 libnvisp_v3 libnvmm libnvmm_utils libnvodm_imager libnvos libnvrm libnvrm_graphics libnvsm libnvtvmr libnvvicsi_v3 libopencv24_tegra libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcontrol_jni
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcontrol_jni.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libhardware_legacy libc libnativehelper libstdc++ libdl libcutils liblog libc libcutils libdl libhardware_legacy liblog libm libnativehelper libnvos libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcapaudioservice
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcapaudioservice.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libmedia libnvos libm libc libnvaudioservice libbinder libnvrm libnvmm_utils libnvcapclk liblog libnvrm_graphics libutils libstlport libbinder libc liblog libm libmedia libnvaudioservice libnvcapclk libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++ libstlport libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtvmr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtvmr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libnvavp libnvddk_2d_v2 libc libm libnvavp libnvddk_2d_v2 libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librm31080
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/librm31080.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcam_imageencoder
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcam_imageencoder.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvtvmr libnvos libm libc libnvrm libnvmm_utils libjpeg libc libjpeg libm libnvmm_utils libnvos libnvrm libnvtvmr libstdc++
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvcam_imageencoder.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_0a_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_0a_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_utils
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_utils.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libcutils libnvrm_graphics libnvavp libnvfusebypass libc libcutils libm libnvavp libnvfusebypass libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvobjecttracking
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvobjecttracking.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libEGL liblog libopencv24_tegra libGLESv2 libEGL libGLESv2 liblog libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvobjecttracking.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvvicsi
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvvicsi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libril-icera
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libril-icera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libcrypto libm libc libnetutils libril libcutils libutils librilutils libc libcrypto libcutils libm libnetutils libril librilutils libstdc++ libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libril-icera.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_tbc
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_tbc.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvwinsys
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvwinsys.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libui libnvos libm libc libbinder libnvrm libstdc++ libgui libcutils libbinder libc libcutils libgui libm libnvos libnvrm libstdc++ libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libussrd
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libussrd.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libnvos libm libc libbinder libstdc++ libdl libcutils liblog libbinder libc libcutils libdl liblog libm libnvos libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvrm_graphics libc libm libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libwvm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libwvm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libnvos libm libWVStreamControlAPI_L1 libc libnvrm libstdc++ libz libcutils libdrmframework liblog libstlport libnvavp libstagefright libWVStreamControlAPI_L1 libc libcutils libdrmframework liblog libm libnvavp libnvos libnvrm libstagefright libstdc++ libstlport libutils libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtsechdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtsechdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libcutils liblog libnvrm_graphics libc libcutils liblog libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_02_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_02_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvisp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvisp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libcuda
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libcuda.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libm libz libc libstdc++ libdl liblog libc libdl liblog libm libstdc++ libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_spincircle
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_spincircle.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_04_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_04_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libphs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libphs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libbinder libstdc++ liblog libbinder libc liblog libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_05_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_05_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_camera
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_camera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvcap
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcap.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libmedia libnvcapaudioservice libm libc libnvaudioservice libbinder libnvcapclk libnvrm libnvmm_utils libcutils liblog libnvhdcp libnvrm_graphics libnvos libutils libstlport libbinder libc libcutils liblog libm libmedia libnvaudioservice libnvcapaudioservice libnvcapclk libnvhdcp libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++ libstlport libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvcapclk
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcapclk.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libnvos libm libc libbinder libnvrm libstdc++ libnvrm_graphics libnvddk_2d_v2 libbinder libc libm libnvddk_2d_v2 libnvos libnvrm libnvrm_graphics libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvhrcv
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhrcv.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libmedia libnvcapaudioservice libm libc libnvaudioservice libbinder libnvcapclk libnvrm libnvmm_utils libcutils liblog libnvos libnvrm_graphics libutils libstlport libbinder libc libcutils liblog libm libmedia libnvaudioservice libnvcapaudioservice libnvcapclk libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++ libstlport libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_parser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_parser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvmm_contentpipe libc libm libnvmm_contentpipe libnvmm_utils libnvos libnvrm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_contentpipe
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_contentpipe.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvrm_graphics libc libm libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libclcore_nvidia
LOCAL_MODULE_SUFFIX := .bc
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libclcore_nvidia.bc
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvblit
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvblit.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics liblog libnvddk_vic libnvgr libsync libc liblog libm libnvddk_vic libnvgr libnvos libnvrm libnvrm_graphics libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_generic
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_generic.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_audio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_audio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmmlite_utils libstdc++ libnvmmlite libm libc libnvrm libnvmm_utils libnvrm_graphics libnvos libc libm libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_il
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_il.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_07_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_07_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := keystore.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/keystore.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libcrypto libm libc libcrypto liblog libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwcomposer.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/hwcomposer.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libEGL libnvhwc_service libnvos libui libm libGLESv2 libc libnvrm libstdc++ libdl libcutils liblog libutils libnvblit libtlk_secure_hdcp_up libnvrm_graphics libnvddk_vic libnvgr libhardware libsync libEGL libGLESv2 libc libcutils libdl libhardware liblog libm libnvblit libnvddk_vic libnvgr libnvhwc_service libnvos libnvrm libnvrm_graphics libstdc++ libsync libtlk_secure_hdcp_up libui libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/hw/hwcomposer.tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := ts.default
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/ts.default.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := memtrack.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/memtrack.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc libstdc++ libcutils liblog libm libc libcutils liblog libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := audio.primary.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/audio.primary.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libaudioutils libmedia libnvcapaudioservice libm libc libexpat libnbaio libnvaudioservice libbinder libtinyalsa libstdc++ libdl libcutils libaudioavp libnvoice libnvaudiofx libnvos libaudiospdif libtinycompress libutils libaudioavp libaudiospdif libaudioutils libbinder libc libcutils libdl libexpat libm libmedia libnbaio libnvaudiofx libnvaudioservice libnvcapaudioservice libnvoice libnvos libstdc++ libtinyalsa libtinycompress libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gralloc.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/gralloc.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libdl libcutils liblog libnvblit libnvrm_graphics libnvgr libsync libc libcutils libdl liblog libm libnvblit libnvgr libnvos libnvrm libnvrm_graphics libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := camera.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/camera.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libmedia libstdc++ libnvgr libnvddk_2d_v2 libcameraservice libnvtvmr libnvos libnvcamerahdr libphs libbinder libcamera_client libnvcam_imageencoder libnvmm libGLESv2 libscf libm libhardware_legacy libc libnvmm_utils libnvrm_graphics libfcamdng libcamera_metadata libutils libui libjpeg libnvrm libgui libcutils libhardware libGLESv2 libbinder libc libcamera_client libcamera_metadata libcameraservice libcutils libfcamdng libgui libhardware libhardware_legacy libjpeg libm libmedia libnvcam_imageencoder libnvcamerahdr libnvddk_2d_v2 libnvgr libnvmm libnvmm_utils libnvos libnvrm libnvrm_graphics libnvtvmr libphs libscf libstdc++ libui libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/hw/camera.tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_audio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_audio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvrm_graphics libnvmm libc libm libnvmm libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrm_graphics
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrm_graphics.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ liblog libsync libc liblog libm libnvos libnvrm libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefright_hdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libstagefright_hdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libnvrm libstagefright_foundation libstdc++ libdl liblog libc libdl liblog libm libnvrm libstagefright_foundation libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_combinator
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_combinator.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtlk_secure_hdcp_up
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtlk_secure_hdcp_up.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm_graphics libstdc++ libtsechdcp libcutils liblog libc libcutils liblog libm libnvos libnvrm_graphics libstdc++ libtsechdcp
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_utils
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_utils.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libnvrm_graphics libc libm libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvddk_vic
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvddk_vic.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics liblog libsync libc liblog libm libnvos libnvrm libnvrm_graphics libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_gpucompute
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_gpucompute.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomx
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomx.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libmedia libstdc++ libnvgr libnvddk_2d_v2 libsync libnvtvmr libnvos libbinder libnvmm libnvmmlite libm libc libnvmm_utils libnvrm_graphics libOpenSLES libnvmmlite_utils libutils libui libnvrm libcutils libnvmm_contentpipe libnvodm_imager libhardware libOpenSLES libbinder libc libcutils libhardware libm libmedia libnvddk_2d_v2 libnvgr libnvmm libnvmm_contentpipe libnvmm_utils libnvmmlite libnvmmlite_utils libnvodm_imager libnvos libnvrm libnvrm_graphics libnvtvmr libstdc++ libsync libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_0b_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_0b_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvos
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvos.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libm libc libphs libstdc++ libdl libcutils liblog libc libcutils libdl liblog libm libphs libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvhdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libm libc libnvrm libnvmm_utils libcutils libnvrm_graphics libc libcutils libm libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_06_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_06_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvddk_2d_v2
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvddk_2d_v2.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libnvddk_vic libc libm libnvddk_vic libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvavp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvavp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvos libnvrm libm libc libm libnvos libnvrm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvisp_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvisp_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcamerahdr_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmm_utils libcutils libopencv24_tegra libnvos libnvrm libcutils libnvmm_utils libnvos libnvrm libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvcamerahdr_v3.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libdrmwvmplugin
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/drm/libdrmwvmplugin.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/drm
LOCAL_REQUIRED_MODULES := libutils libnvos libm libWVStreamControlAPI_L1 libc libbinder libnvrm libstdc++ libdl libcutils liblog libz libnvavp libwvdrm_L1 libstlport libWVStreamControlAPI_L1 libbinder libc libcutils libdl liblog libm libnvavp libnvos libnvrm libstdc++ libstlport libutils libwvdrm_L1 libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvparser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvparser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvos libnvrm libm libc libm libnvos libnvrm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrmapi_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrmapi_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libdl libstdc++ libm libz libc libdl libm libstdc++ libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvodm_imager
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvodm_imager.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libcutils liblog libnvrm_graphics libc libcutils liblog libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_graphics
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_graphics.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcms
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcms.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ libnvrm_graphics liblog libc liblog libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvfusebypass
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvfusebypass.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvmmlite_utils libstdc++ libnvos libm libc libnvmm_utils libc libm libnvmm_utils libnvmmlite_utils libnvos libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvgr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvgr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libm libc libstdc++ libcutils libhardware libsync libc libcutils libhardware libm libstdc++ libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtnr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtnr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvtvmr libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libm libnvos libnvrm libnvrm_graphics libnvtvmr libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_boot
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_boot.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ liblog libussrd libm libc liblog libm libstdc++ libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_01_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_01_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefrighthw
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libstagefrighthw.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libutils libm libc libstdc++ libdl liblog libc libdl liblog libm libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtestio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtestio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libnvos libnvapputil libm libc libm libnvapputil libnvos libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv2_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libGLESv2_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libglcore libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libglcore libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv1_CM_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libGLESv1_CM_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libglcore libnvos libm libc libnvrm libstdc++ libnvrm_graphics libc libglcore libm libnvos libnvrm libnvrm_graphics libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libEGL_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libEGL_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libm libz libnvcpl libphs libstdc++ libc libcutils libdl libnvglsi libsync libc libcutils libdl libm libstdc++ libsync libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameradata
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcameradata.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvviccomposer
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvviccomposer.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libinvensense_hal
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libinvensense_hal.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc libstdc++ libmplmpu libm libmllite libc libm libmllite libmplmpu libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvgpudenoise
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvgpudenoise.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvchimerashaderstore
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvchimerashaderstore.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtbb
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libtbb.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libtbb.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := _nvcameratools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_nvcameratools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libnvos libm libpython2.6 libc libnvcameratools libstdc++ libstlport libc libm libnvcameratools libnvos libpython2.6 libstdc++ libstlport
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := datetime
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/datetime.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := binascii
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/binascii.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _weakref
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_weakref.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _struct
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_struct.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _multibytecodec
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_multibytecodec.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _collections
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_collections.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := time
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/time.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _functools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_functools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := strop
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/strop.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _socket
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_socket.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cmath
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/cmath.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _nvcamera_v1
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_nvcamera_v1.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libstdc++ libnvos libnvomxilclient libm libnvomx libc libnvwinsys libnvrm libnvmm_utils libnvrm_graphics libpython2.6 libnvmm_contentpipe libnvmm libstlport libc libm libnvmm libnvmm_contentpipe libnvmm_utils libnvomx libnvomxilclient libnvos libnvrm libnvrm_graphics libnvwinsys libpython2.6 libstdc++ libstlport
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _fileio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_fileio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := unicodedata
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/unicodedata.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fcntl
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/fcntl.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _random
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/_random.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := array
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/array.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := operator
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/operator.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := parser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/parser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := select
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/python2.6/lib-dynload/select.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libpython2.6 libc libm libpython2.6 libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libhdcp_up
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libhdcp_up.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liboemcrypto
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/liboemcrypto.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libm libc libnvrm libstdc++ liblog libnvavp libstlport libc liblog libm libnvavp libnvos libnvrm libstdc++ libstlport
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcudaslidingdct
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcudaslidingdct.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libnvcudaslidingdct.a_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libmonitor
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libmonitor.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr_expfusion
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcamerahdr_expfusion.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libopencv24_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libopencv24_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libEGL libGLESv2 libdl libjpeg liblog libz libpng libtbb libEGL libGLESv2 libdl libjpeg liblog libpng libtbb libz
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libopencv24_tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libpython2.6
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libpython2.6.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc libdl libstdc++ libm libc libdl libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmplmpu
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libmplmpu.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameraframedata
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcameraframedata.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr_expfusion_v3
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcamerahdr_expfusion_v3.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := warmboot
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/warmboot.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvbdktestbl
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvbdktestbl.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp1x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp1x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2xtest.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2xtest.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_eff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_os_eff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegra_xusb_firmware
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra_xusb_firmware
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_0ff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_os_0ff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_mp3dec_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_mp3dec_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegra12x_xusb_firmware
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x_xusb_firmware
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_aud_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_aud_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_8ff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_os_8ff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_f7e00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_os_f7e00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_aacdec_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_aacdec_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_vid_ucode_alt.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/nvavp_vid_ucode_alt.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NETB_img.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/gk20a/NETB_img.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fecs.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/gk20a/fecs.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gpccs.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/gk20a/gpccs.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gpmu_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/gk20a/gpmu_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vic03_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x/vic03_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvhost_msenc031.fw
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x/nvhost_msenc031.fw
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvhost_tsec.fw
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x/nvhost_tsec.fw
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tos
LOCAL_MODULE_SUFFIX := .img
LOCAL_SRC_FILES := target/product/shieldtablet/tos.img
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvml
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvml.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := secure_otf
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/secure_otf_intermediates/secure_otf
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := crypto_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/crypto_service_intermediates/crypto_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := oemcrypto_secure_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/oemcrypto_secure_service_intermediates/oemcrypto_secure_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := trusted_app
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/trusted_app_intermediates/trusted_app
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwkeystore_task
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/hwkeystore_task_intermediates/hwkeystore_task
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := secure_rtc
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/secure_rtc_intermediates/secure_rtc
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := storage_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/storage_service_intermediates/storage_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp_secure_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/hdcp_secure_service_intermediates/hdcp_secure_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tlkstoragedemo_task
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/tlkstoragedemo_task_intermediates/tlkstoragedemo_task
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := trusted_app2
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/trusted_app2_intermediates/trusted_app2
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvtboot
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvtboot.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvtboot_recovery
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvtboot_recovery.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libstdc++ libm libc libm libstdc++
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
include $(BUILD_COPY_HEADERS)
